In [2]:
import torch

# 1. 加载.pt文件（替换为你的文件路径）
file_path = "/home/bohao/LuvRobot/Y1_1Pace/data/Y1_1_sim/chrip_data.pt"
data = torch.load(file_path)


In [3]:
# 2. 第一步：查看数据的类型和基本信息（关键）
print("=== 数据基本信息 ===")
print(f"数据类型: {type(data)}")  # 常见类型：torch.Tensor、dict、list、tuple等


=== 数据基本信息 ===
数据类型: <class 'dict'>


In [4]:
# 3. 分类型查看详细内容
if isinstance(data, torch.Tensor):
    # 场景1：数据是张量（最常见）
    print(f"张量形状: {data.shape}")
    print(f"张量数据类型: {data.dtype}")
    print(f"张量设备: {data.device}")  # 查看数据在CPU/GPU
    print(f"前5行前5列数据:\n{data[:5, :5]}")  # 预览部分数据
    print(f"数据范围: 最小值={data.min().item()}, 最大值={data.max().item()}")

elif isinstance(data, dict):
    # 场景2：数据是字典（常用，存储多组数据）
    print(f"字典的键: {list(data.keys())}")
    # 遍历每个键的值
    for key, value in data.items():
        print(f"\n--- 键: {key} ---")
        print(f"值类型: {type(value)}")
        if isinstance(value, torch.Tensor):
            print(f"值形状: {value.shape}")
            print(f"值示例:\n{value[:3]}")  # 预览前3个元素

elif isinstance(data, list) or isinstance(data, tuple):
    # 场景3：数据是列表/元组
    print(f"列表/元组长度: {len(data)}")
    # 查看前3个元素
    for i, item in enumerate(data[:3]):
        print(f"\n--- 第{i}个元素 ---")
        print(f"类型: {type(item)}")
        if isinstance(item, torch.Tensor):
            print(f"形状: {item.shape}")
            print(f"示例:\n{item[:2]}")

字典的键: ['time', 'dof_pos', 'des_dof_pos']

--- 键: time ---
值类型: <class 'torch.Tensor'>
值形状: torch.Size([10000])
值示例:
tensor([0.0000, 0.0020, 0.0040])

--- 键: dof_pos ---
值类型: <class 'torch.Tensor'>
值形状: torch.Size([10000, 6])
值示例:
tensor([[ 0.1000,  0.3000,  0.4200, -0.0200,  0.1600,  0.3400],
        [ 0.0996,  0.3003,  0.4197, -0.0203,  0.1598,  0.2957],
        [ 0.0992,  0.3001,  0.4194, -0.0209,  0.1595,  0.2940]])

--- 键: des_dof_pos ---
值类型: <class 'torch.Tensor'>
值形状: torch.Size([10000, 6])
值示例:
tensor([[ 0.0000,  0.2000,  0.3200, -0.1200,  0.0600,  0.2400],
        [ 0.0013,  0.2013,  0.3213, -0.1187,  0.0613,  0.2413],
        [ 0.0025,  0.2025,  0.3225, -0.1175,  0.0625,  0.2425]])


In [5]:
import torch

# 1. 加载.pt文件（替换为你的文件路径）
file_path = "/home/bohao/LuvRobot/Y1_1Pace/data/Y1_1_sim/sim_data.pt"
data = torch.load(file_path)

In [6]:
# 2. 第一步：查看数据的类型和基本信息（关键）
print("=== 数据基本信息 ===")
print(f"数据类型: {type(data)}")  # 常见类型：torch.Tensor、dict、list、tuple等

=== 数据基本信息 ===
数据类型: <class 'dict'>


In [7]:
# 3. 分类型查看详细内容
if isinstance(data, torch.Tensor):
    # 场景1：数据是张量（最常见）
    print(f"张量形状: {data.shape}")
    print(f"张量数据类型: {data.dtype}")
    print(f"张量设备: {data.device}")  # 查看数据在CPU/GPU
    print(f"前5行前5列数据:\n{data[:5, :5]}")  # 预览部分数据
    print(f"数据范围: 最小值={data.min().item()}, 最大值={data.max().item()}")

elif isinstance(data, dict):
    # 场景2：数据是字典（常用，存储多组数据）
    print(f"字典的键: {list(data.keys())}")
    # 遍历每个键的值
    for key, value in data.items():
        print(f"\n--- 键: {key} ---")
        print(f"值类型: {type(value)}")
        if isinstance(value, torch.Tensor):
            print(f"值形状: {value.shape}")
            print(f"值示例:\n{value[:3]}")  # 预览前3个元素

elif isinstance(data, list) or isinstance(data, tuple):
    # 场景3：数据是列表/元组
    print(f"列表/元组长度: {len(data)}")
    # 查看前3个元素
    for i, item in enumerate(data[:3]):
        print(f"\n--- 第{i}个元素 ---")
        print(f"类型: {type(item)}")
        if isinstance(item, torch.Tensor):
            print(f"形状: {item.shape}")
            print(f"示例:\n{item[:2]}")

字典的键: ['time', 'dof_pos', 'des_dof_pos']

--- 键: time ---
值类型: <class 'torch.Tensor'>
值形状: torch.Size([15000])
值示例:
tensor([0.0000, 0.0020, 0.0040])

--- 键: dof_pos ---
值类型: <class 'torch.Tensor'>
值形状: torch.Size([15000, 5])
值示例:
tensor([[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [-2.6756e-09,  4.7402e-05, -9.5241e-04,  2.8686e-03, -7.1068e-04],
        [-4.7742e-08,  1.7500e-04, -3.7612e-03,  1.1414e-02, -2.7632e-03]])

--- 键: des_dof_pos ---
值类型: <class 'torch.Tensor'>
值形状: torch.Size([15000, 5])
值示例:
tensor([[ 2.0000e-02,  0.0000e+00,  0.0000e+00,  1.0400e+00, -3.4000e-01],
        [ 2.0252e-02,  5.0431e-04,  7.5647e-04,  1.0409e+00, -3.3899e-01],
        [ 2.0506e-02,  1.0119e-03,  1.5179e-03,  1.0418e+00, -3.3798e-01]])
